#1- workflow name
name: house_price_estimator CI pipeline


#5- define envirements to make connection between gcp and github
env:
  SERVICE_NAME: house_price_estimator
  PROJECT_ID: friendly-bazaar-446014-s8
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/friendly-bazaar-446014-s8/flask-houseprice:latest


#2- when it starts? on push or pull_request to the main branch
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

#3- What should it do? (define the steps of the job)
jobs:
  build-and-test:
    # define operating system
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # my code is pythonic
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: train the model (online training)
        run: python model.py
        
      - name: Run tests with pytest
        run: pytest

  #4- cd process
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository or code
        uses: actions/checkout@v3

      - name: Athenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCP_KEY_1}}

      - name: Configure GCP project
        run:
          gcloud config set project friendly-bazaar-446014-s8

      - name: build-and-push Docker image 
        run: |
          docker build -t flask-houseprice:latest 
          gcloud auth configure-docker europe-west10-docker.pkg.dev
          docker push europe-west10-docker.pkg.dev/friendly-bazaar-446014-s8/flask-houseprice:latest
