#1- workflow name
name: house_price_estimator CI pipeline

#5- define environments to make connection between GCP and GitHub
env:
  SERVICE_NAME: house_price_estimator
  PROJECT_ID: friendly-bazaar-446014-s8
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/friendly-bazaar-446014-s8/flask-houseprice:latest

#2- when it starts? on push or pull_request to the main branch
on:
  push:
    branches:
      - do-not-run-this-branch

  pull_request:
    branches:
      - do-not-run-this-branch #main

#3- What should it do? (define the steps of the job)
jobs:
  build-and-test:
    # define operating system
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # my code is pythonic
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Train the model (online training)
        run: python model.py
        
      - name: Run tests with pytest
        run: pytest

  #4- cd process
  deploy:
    needs: build-and-test #in default both build and deploy process at same time. now one by one
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository or code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_1 }}

      - name: Configure GCP project
        run: gcloud config set project ${{ env.PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }} .
          gcloud auth configure-docker europe-west10-docker.pkg.dev
          docker push ${{ env.DOCKER_IMAGE_URL }}
